# Generated by Django 5.0.2 on 2024-03-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestType',
        ),
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pettype'),
        ),
        migrations.AddField(
            model_name='pet',
            name='phone',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
